### Código utilizado en el video:
https://youtu.be/-LZ609NdCXQ

In [1]:
import pandas as pd

In [2]:
vendedores_df = pd.read_excel('pandas 7 - datos de vendedores.xlsx')

In [3]:
vendedores_df.head(10)

,NOMBRE,APELLIDO,EMAIL,FECHA INGRESO,VENTAS,CALIFICACION DADA POR LOS CLIENTES,TELEFONO
0,Luciana,Rodríguez,l.rodriguez@ventas.com.br,2021-08-01,180,MUY BUENA,324309
1,Santiago,González,s.gonzalez@ventas.com.uy,2013-12-03,130,MALA,310277
2,Paola,Gómez,p.gomez@ventas.com.co,2014-11-20,198,MUY BUENA,29938
3,Carlos,Fernández,c.fernandez@ventas.com.br,2022-03-14,150,MALA,607278
4,Jonathan,López,j.lopez@ventas.com.py,2018-07-19,135,MALA,188245
5,Gabriela,Martínez,g.martinez@ventas.com.cl,2019-10-07,148,BUENA,964823
6,Ezequiel,Romero,e.romero@ventas.com.cl,2017-10-06,220,EXCELENTE,989089
7,Maximiliano,Torres,m.torres@ventas.com.ar,2015-01-05,155,BUENA,998536
8,Julieta,Ruiz,j.ruiz@ventas.com.uy,2016-09-03,219,EXCELENTE,510030
9,Mariano,Suarez,m.suarez@ventas.com.ar,2013-04-17,200,EXCLENTE,252144

In [4]:
region_asignada = []

for item in vendedores_df['EMAIL']:
    if '.ar' in item:
        region_asignada.append('Argentina')
    elif '.br' in item:        
        region_asignada.append('Brasil')
    elif '.uy' in item:
        region_asignada.append('Uruguay')
    elif '.py' in item:
        region_asignada.append('Paraguay')
    elif '.ec' in item:
        region_asignada.append('Ecuador')
    elif '.cl' in item:
        region_asignada.append('Chile')
    elif '.co' in item:
        region_asignada.append('Colombia')
    else:
        region_asignada.append('Región no Asignada')

In [5]:
vendedores_df['REGION'] = region_asignada
vendedores_df.tail(10)

,NOMBRE,APELLIDO,EMAIL,FECHA INGRESO,VENTAS,CALIFICACION DADA POR LOS CLIENTES,TELEFONO,REGION
32,Marina,Ordoñez,m.ordonez@ventas.com.ar,2018-09-03,190,MUY BUENA,931214,Argentina
33,Eduardo,Paredes,e.paredes@ventas.com.ec,2017-09-05,187,MUY BUENA,436084,Ecuador
34,Esteban,Bustamante,e.bustamante@ventas.com.co,2019-02-03,170,BUENA,778410,Colombia
35,Cecilia,Pacheco,c.pacheco@ventas.com.br,2022-05-09,180,MUY BUENA,531929,Brasil
36,Isabel,Guevara,i.guevara@ventas.com.br,2019-11-10,135,MALA,230045,Brasil
37,Hugo,Aquino,h.aquino@ventas.com.ar,2016-12-12,140,MALA,851120,Argentina
38,Lucas,Alegre,l.alegre@ventas.com.cl,2014-01-13,150,BUENA,280022,Chile
39,Miguel,Prieto,mi.prieto@ventas.com.py,2014-08-25,160,BUENA,606234,Paraguay
40,Daniel,Funes,d.funes@ventas.com.uy,2013-06-27,180,MUY BUENA,220303,Uruguay
41,Fernando,Ibarra,f.ibarra@ventas.com.ar,2021-05-20,190,MUY BUENA,298007,Argentina

In [6]:
vendedores_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   NOMBRE                              42 non-null     object
 1   APELLIDO                            42 non-null     object
 2   EMAIL                               42 non-null     object
 3   FECHA INGRESO                       42 non-null     datetime64[ns]
 4   VENTAS                              42 non-null     int64
 5   CALIFICACION DADA POR LOS CLIENTES  42 non-null     object
 6   TELEFONO                            42 non-null     int64
 7   REGION                              42 non-null     object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 2.8+ KB

In [7]:
vendedores_df['TELEFONO'] = vendedores_df['TELEFONO'].astype(str)
vendedores_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   NOMBRE                              42 non-null     object
 1   APELLIDO                            42 non-null     object
 2   EMAIL                               42 non-null     object
 3   FECHA INGRESO                       42 non-null     datetime64[ns]
 4   VENTAS                              42 non-null     int64
 5   CALIFICACION DADA POR LOS CLIENTES  42 non-null     object
 6   TELEFONO                            42 non-null     object
 7   REGION                              42 non-null     object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 2.8+ KB

In [8]:
i = 0

nuevos_telefonos = []

for item in vendedores_df['EMAIL']:    
    if '.ar' in item:        
        nuevo_telefono = '+54-' + vendedores_df.iloc[i]['TELEFONO']        
        nuevos_telefonos.append(nuevo_telefono)
    elif '.br' in item:        
        nuevo_telefono = '+55-' + vendedores_df.iloc[i]['TELEFONO']
        nuevos_telefonos.append(nuevo_telefono)
    elif '.uy' in item:
        nuevo_telefono = '+598-' + vendedores_df.iloc[i]['TELEFONO']
        nuevos_telefonos.append(nuevo_telefono)
    elif '.py' in item:
        nuevo_telefono = '+595-' + vendedores_df.iloc[i]['TELEFONO']
        nuevos_telefonos.append(nuevo_telefono)
    elif '.ec' in item:
        nuevo_telefono = '+593-' + vendedores_df.iloc[i]['TELEFONO']
        nuevos_telefonos.append(nuevo_telefono)
    elif '.cl' in item:
        nuevo_telefono = '+56-' + vendedores_df.iloc[i]['TELEFONO']        
        nuevos_telefonos.append(nuevo_telefono)
    elif '.co' in item:
        nuevo_telefono = '+57-' + vendedores_df.iloc[i]['TELEFONO']
        nuevos_telefonos.append(nuevo_telefono)
    i +=1

In [9]:
vendedores_df['TELEFONO'] = nuevos_telefonos

In [10]:
vendedores_df.head(10)

,NOMBRE,APELLIDO,EMAIL,FECHA INGRESO,VENTAS,CALIFICACION DADA POR LOS CLIENTES,TELEFONO,REGION
0,Luciana,Rodríguez,l.rodriguez@ventas.com.br,2021-08-01,180,MUY BUENA,+55-324309,Brasil
1,Santiago,González,s.gonzalez@ventas.com.uy,2013-12-03,130,MALA,+598-310277,Uruguay
2,Paola,Gómez,p.gomez@ventas.com.co,2014-11-20,198,MUY BUENA,+57-29938,Colombia
3,Carlos,Fernández,c.fernandez@ventas.com.br,2022-03-14,150,MALA,+55-607278,Brasil
4,Jonathan,López,j.lopez@ventas.com.py,2018-07-19,135,MALA,+595-188245,Paraguay
5,Gabriela,Martínez,g.martinez@ventas.com.cl,2019-10-07,148,BUENA,+56-964823,Chile
6,Ezequiel,Romero,e.romero@ventas.com.cl,2017-10-06,220,EXCELENTE,+56-989089,Chile
7,Maximiliano,Torres,m.torres@ventas.com.ar,2015-01-05,155,BUENA,+54-998536,Argentina
8,Julieta,Ruiz,j.ruiz@ventas.com.uy,2016-09-03,219,EXCELENTE,+598-510030,Uruguay
9,Mariano,Suarez,m.suarez@ventas.com.ar,2013-04-17,200,EXCLENTE,+54-252144,Argentina